@startuml
title Séquences d'États Observées (T2S)

skinparam state {
  BackgroundColor LightBlue
  BorderColor Blue
  ArrowColor Black
}

state "1. Cycle Nominal : Arrêt déclenché par la voiture (EV)" as CycleNominal {
  state "Repos" as A1
  state "Connecté" as B1
  state "Attente EV" as C1
  state "En Charge" as DE1
  state "Interrompu par EV" as I1
  state "Débranchement" as L1

  [*] --> A1
  A1 --> B1 : Branchement
  B1 --> C1 : Borne autorise
  C1 --> DE1 : EV tire le courant
  DE1 --> I1 : EV arrête la charge
  I1 --> B1 : Repos branché
  B1 --> L1 : Câble retiré (SBF:0)
  L1 --> A1 : Libération
  A1 --> [*]
}

state "2. Arrêt forcé par la Borne (via commande locale)" as CycleForce {
  state "Repos" as A2
  state "Connecté" as B2
  state "Attente EV" as C2
  state "En Charge" as DE2
  state "Arrêt en cours" as W2
  state "Arrêt terminé" as M2

  [*] --> A2
  A2 --> B2 : Branchement
  B2 --> C2 : Borne autorise
  C2 --> DE2 : EV tire le courant
  DE2 --> W2 : Ordre T2CNOK
  W2 --> M2 : Envoi Résumé Session
  M2 --> A2 : Libération virtuelle
  A2 --> [*]
}
@enduml
